version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: oficina_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: oficina_mecanica
      POSTGRES_USER: oficina_user
      POSTGRES_PASSWORD: oficina_password123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oficina_user -d oficina_mecanica"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
